Class: "Service"
Definitions:
  azure-virtual-network:
    Fields:
      Name: "Virtual Network"
      Description: "Virtual Network"
      Link: "https://azure.microsoft.com/en-gb/services/virtual-network/"
    References: [
      { Class: "ServiceProvider", ID: "azure", Relationship: "PROVIDED_BY" },
    ]

    SubDefinitions:
      CONFIGURED_IN:
        Class: "ServiceConfiguration"
        Definitions:
          azure-virtual-network-default:
            References: [
              { Class: "ServiceSubcategory", ID: "virtual-network", Relationship: "BELONGS_TO" },
              { Class: "ServiceTenancy", ID: "serverless", Relationship: "HAS_TENANCY_OF" },
            ]