Class: "Service"
Definitions:
  aws-application-load-balancer:
    Fields:
      Name: "Application Load Balancer"
      Description: "AWS Application Load Balancer"
      Link: "https://aws.amazon.com/elasticloadbalancing/application-load-balancer/"
    References: [
      { Class: "Provider", ID: "aws", Relationship: "PROVIDED_BY" },
      { Class: "Capability", ID: "load-balancer", Relationship: "PROVIDES" },
      { Class: "Tenancy", ID: "managed", Relationship: "HAS_TENANCY" }
    ]