Class: "ServiceCapability"
Definitions:
  application-integration:
    Fields:
      Name: "application integration"
      Description: "Application Integration"
      Order: "06"

    SubDefinitions:
      PROVIDED_BY:
        Class: "ServiceCategory"
        Definitions:
          queue:
            Fields:
              Name: "queue"
              Description: "Queue"
              Order: "01"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  unordered-queue:
                    Fields:
                      Name: "unordered-queue"
                      Description: "Queue where the order is not guaranteed"
                      Order: "01"
                  ordered-queue:
                    Fields:
                      Name: "ordered queue"
                      Description: "Queue where the order is guaranteed"
                      Order: "02"

          notification:
            Fields:
              Name: "notification"
              Description: "Notification"
              Order: "02"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  notification:
                    Fields:
                      Name: "notification"
                      Description: "Notification"
                      Order: "01"

          api-management:
            Fields:
              Name: "api management"
              Description: "API Management"
              Order: "03"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  api-management:
                    Fields:
                      Name: "api management"
                      Description: "API Management"
                      Order: "01"

          media-transcoding:
            Fields:
              Name: "media transcoding"
              Description: "Media Transcoding"
              Order: "04"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  media-transcoding:
                    Fields:
                      Name: "media transcoding"
                      Description: "Media Transcoding"
                      Order: "01"



          email:
            Fields:
              Name: "email"
              Description: "Email"
              Order: "05"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  email:
                    Fields:
                      Name: "email"
                      Description: "Email"
                      Order: "01"

          blockchain:
            Fields:
              Name: "blockchain"
              Description: "Blockchain"
              Order: "06"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  blockchain:
                    Fields:
                      Name: "blockchain"
                      Description: "Blockchain"
                      Order: "01"

          chatbot:
            Fields:
              Name: "chatbot"
              Description: "Chatbot"
              Order: "07"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  chatbot:
                    Fields:
                      Name: "chatbot"
                      Description: "Chatbot"
                      Order: "01"