image: nextmetaphor/yaml-graph:latest
pages:
  stage: deploy
  script:
    - sleep 20
    - yaml-graph validate -f definition/definition-format.yml
    - yaml-graph load

    # generate table report
    - yaml-graph report -f report/table-report/fields.yaml -t report/table-report/template.gohtml > report/table-report/table-report.html
    - cp report/table-report/table-report.html public/index.html

    # generate JSON documents
    - yaml-graph report -f report/ServiceByProviderJSON/fields.yaml -t report/ServiceByProviderJSON/template.gohtml > report/ServiceByProviderJSON/document.json
    - cp report/ServiceByProviderJSON/document.json public/ServiceByProvider.json

    - yaml-graph report -f report/ServiceProviderJSON/fields.yaml -t report/ServiceProviderJSON/template.gohtml > report/ServiceProviderJSON/document.json
    - cp report/ServiceProviderJSON/document.json public/ServiceProviderJSON.json

    - yaml-graph report -f report/ServiceTenancyJSON/fields.yaml -t report/ServiceTenancyJSON/template.gohtml > report/ServiceTenancyJSON/document.json
    - cp report/ServiceTenancyJSON/document.json public/ServiceTenancyJSON.json

    - yaml-graph report -f report/ServiceCapabilityJSON/fields.yaml -t report/ServiceCapabilityJSON/template.gohtml > report/ServiceCapabilityJSON/document.json
    - cp report/ServiceCapabilityJSON/document.json public/ServiceCapabilityJSON.json

    - yaml-graph report -f report/ServiceByCapabilityJSON/fields.yaml -t report/ServiceByCapabilityJSON/template.gohtml > report/ServiceByCapabilityJSON/document.json
    - cp report/ServiceByCapabilityJSON/document.json public/ServiceByCapabilityJSON.json

    - yaml-graph graph > report/3dVisualisation/dataset.json
    - cp report/3dVisualisation/index.html public/3d-visualisation.html
    - cp report/3dVisualisation/dataset.json public/dataset.json

  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
