image: nextmetaphor/yaml-graph:latest
pages:
  stage: deploy
  script:
    - sleep 20
    - yaml-graph validate -f definition/definition-format.yml
    - yaml-graph load
    - yaml-graph report -f report/table-report/fields.yaml -t report/table-report/template.gohtml > report/table-report/table-report.html
    - yaml-graph report -f report/ServiceByProviderJSON/fields.yaml -t report/ServiceByProviderJSON/template.gohtml > report/ServiceByProviderJSON/ServiceByProvider.json
    - cp report/by-blueprint-category/by-blueprint-category.html public/index.html
    - cp report/ServiceByProviderJSON/ServiceByProvider.json public/ServiceByProvider.json
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
