Class: "Service"
Definitions:
  aws-serverless-application-repository:
    Fields:
      Name: "AWS Serverless Application Repository"
      Description: "The AWS Serverless Application Repository is a managed repository for serverless applications."
      Link: "https://aws.amazon.com/serverless/serverlessrepo/"
    FileFields:
      ImgSrc: { Path: "../icons/Asset-Package_09172021/Architecture-Service-Icons_09172021/Arch_Compute/16/Arch_AWS-Serverless-Application-Repository_16.svg", Prefix: "svg+xml;base64,", Encoding: "base64" }
    References: [
      { Class: "ServiceProvider", ID: "aws", Relationship: "PROVIDED_BY" },
    ]

    SubDefinitions:
      CONFIGURED_IN:
        Class: "ServiceConfiguration"
        Definitions:
          aws-serverless-application-repository-default:
            References: [
              { Class: "ServiceSubcategory", ID: "serverless-service-catalog-management", Relationship: "BELONGS_TO" },
              { Class: "ServiceTenancy", ID: "serverless", Relationship: "HAS_TENANCY_OF" }
            ]