Class: "Service"
Definitions:
  aws-application-load-balancer:
    Fields:
      Name: "Application Load Balancer"
      Description: "AWS Application Load Balancer"
      Link: "https://aws.amazon.com/elasticloadbalancing/application-load-balancer/"
    FileFields:
      ImgSrc: { Path: "../icons/Asset-Package_09172021/Resource-Icons_07302021/Res_Networking-and-Content-Delivery/Res_48_Dark/Res_Elastic-Load-Balancing_Application-Load-Balancer_48_Dark.svg", Prefix: "svg+xml;base64,", Encoding: "base64" }
    References: [
      { Class: "ServiceProvider", ID: "aws", Relationship: "PROVIDED_BY" },
    ]

    SubDefinitions:
      CONFIGURED_IN:
        Class: "ServiceConfiguration"
        Definitions:
          aws-application-load-balancer-default:
            References: [
              { Class: "ServiceSubcategory", ID: "layer-7-load-balancer", Relationship: "BELONGS_TO" },
              { Class: "ServiceTenancy", ID: "serverless", Relationship: "HAS_TENANCY_OF" },
            ]