Class: "ServiceCapability"
Definitions:
  application-integration:
    Fields:
      Name: "application integration"
      Description: "Application Integration"
      Order: "07"

    SubDefinitions:
      PROVIDED_BY:
        Class: "ServiceCategory"
        Definitions:
          queue:
            Fields:
              Name: "queue"
              Description: "Queue"
              Order: "01"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  unordered-queue:
                    Fields:
                      Name: "unordered queue"
                      Description: "Queue where the order is not guaranteed"
                      Order: "01"
                  ordered-queue:
                    Fields:
                      Name: "ordered queue"
                      Description: "Queue where the order is guaranteed"
                      Order: "02"
                  activeMQ-compatible:
                    Fields:
                      Name: "activeMQ compatible"
                      Description: "ActiveMQ compatible"
                      Order: "03"
                  rabbitMQ-compatible:
                    Fields:
                      Name: "rabbitMQ compatible"
                      Description: "RabbitMQ compatible"
                      Order: "04"

          notification:
            Fields:
              Name: "notification"
              Description: "Notification"
              Order: "02"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  notification:
                    Fields:
                      Name: "notification"
                      Description: "Notification"
                      Order: "01"

          event-bus:
            Fields:
              Name: "event bus"
              Description: "Event Bus"
              Order: "03"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  event-bus:
                    Fields:
                      Name: "event bus"
                      Description: "Event Bus"
                      Order: "01"

          api-management:
            Fields:
              Name: "api management"
              Description: "API Management"
              Order: "04"
            SubDefinitions:
              GROUPED_BY:
                Class: "ServiceSubcategory"
                Definitions:
                  api-management:
                    Fields:
                      Name: "api management"
                      Description: "API Management"
                      Order: "01"